name: FlameCore
description: Главный управляющий модуль сервера FlameDex
version: '${project.version}'
main: me.jonycape.dev.flamecore.Main
api-version: '1.20'
load: POSTWORLD

authors: [ jonycape ]
website: www.flamedon.ru
softdepend: [ PlaceholderAPI ]

commands:
  giveaway:
    description: Управление конкурсами
    usage: /giveaway create <prize> <time> | /giveaway join <id>
  flamecore:
    description: Главная команда плагина FlameCore
    aliases: [fc]
  stream:
    description: Анонс стрима на весь сервер
    usage: /stream <ссылка>
    permission: flamecore.stream

permissions:
  flamecore.admin:
    description: Доступ к админским функциям FlameCore
    default: op
  flamecore.customize:
    description: Кастомизация персонажа (свечение, попугай, нимб)
    default: op
  flamecore.stream:
    description: Анонс стрима на весь сервер
    default: op